version: "2.1"

services:
  db:
    image: postgres:alpine
    container_name: pandahack_db
    env_file: .env

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5



  app:
    build: .
    image: pandahack
    container_name: pandahack_app
    env_file: .env
    ports:
      - 8080:$APP_PORT
    links:
      - db:$POSTGRES_ADDR

    depends_on:
      db:
        condition: service_healthy


